version: 2

models:
  - name: customers
    description: The enriched customer table
    columns:
      - name: customer_id
        description: the unique id of a customer
        tests:
          - unique
          - not_null
      - name: order_first_date
        description: the date of the first order of a customer, is NULL for customers without at least one order

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
